#Day 2: 30 Days of python programming'

first_name, last_name, full_name, country, city, age, is_married, is_true, is_light_on, skills = "vyas", "sn", "vyas sn", "India", "Madurai", 22, False, True, True, ["Python", "Java", "C++"]
print("First Name:", first_name)
print("Last Name:", last_name)
print("Full Name:", full_name)
print("Country:", country)
print("City:", city)
print("Age:", age)  
print("Is Married:", is_married)
print("Is True:", is_true)
print("Is Light On:", is_light_on)
print("Skills:", skills)
length_of_first_name = len(first_name)
length_of_last_name = len(last_name)
length_of_full_name = len(full_name)
length_of_country = len(country)
length_of_city = len(city)
length_of_age = len(str(age))
length_of_is_married = len(str(is_married))
length_of_is_true = len(str(is_true))
length_of_is_light_on = len(str(is_light_on))
length_of_skills = len(str(skills)) 
#Using the len() built-in function, find the length of your first name
print("Length of first name:", length_of_first_name)
#Using the len() built-in function, find the length of your last name
print("Length of last name:", length_of_last_name)
print("Length of full name:", length_of_full_name)
print("Length of country:", length_of_country)
print("Length of city:", length_of_city)
print("Length of age:", length_of_age)
print("Length of is married:", length_of_is_married)
print("Length of is true:", length_of_is_true)
print("Length of is light on:", length_of_is_light_on)
print("Length of skills:", length_of_skills)
